[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 150
target-version = "py311"
select = ["E", "F", "I"]  # Enforce best practices, catching errors & import sorting
ignore = []  # You can add ignored rules if needed

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
strict = true
